// Verified project data from live pages
export const PROJECTS = [
  {
    id: 1,
    title: "EduMate — Student Mentoring & Document Management System",
    shortTitle: "EduMate",
    description: "A mentoring and document-management platform built for Sri Sairam Engineering College, streamlining how students, mentors, and administration interact.",
    category: ["Academic Systems", "Web"],
    tags: ["React", "Onspace", "Academic Systems"],
    liveLink: "https://preview-react-9b5loa-gq5dby2vz4fvj9mmfxoqqy.onspace.build/?_q=GQ5dBY2vz4FVJ9mmfXoqqy",
    githubRepo: "https://github.com/Thanajayan143/EduMate",
    repoName: "EduMate",
    accent: "#00c4f5",
    icon: "🎓",
  },
  {
    id: 2,
    title: "SaiNex Technologies — Company Website",
    shortTitle: "SaiNex Company Site",
    description: "The official brand site for SaiNex Technologies, presenting the company's Web Development, Mobile Apps, AI, Automation, Cybersecurity, IoT, and Technical Consulting focus areas.",
    category: ["Web", "Brand"],
    tags: ["React", "Onspace", "Brand/Company"],
    liveLink: "https://preview-react-9bij5y-lafrjykyb6hzgnkzebxlkr.onspace.build/?_q=LAFRjyKyb6hzGNKZEbxLKr",
    githubRepo: null,
    repoName: null,
    accent: "#0077b6",
    icon: "🏢",
  },
  {
    id: 3,
    title: "Smart Industrial Air Monitoring & Worker Safety System",
    shortTitle: "Air Monitoring & Safety",
    description: "An IoT-powered concept for real-time industrial air-quality monitoring and instant safety alerts, built for the Sairam SDG Ideathon.",
    category: ["IoT", "Hardware", "Automation"],
    tags: ["IoT", "Sensors", "React", "Sairam SDG Ideathon"],
    liveLink: "https://preview-react-9bh9gh-j3ryrujjnlcyxxdxnrlbtq.onspace.build/?_q=j3RYrUjjnLCyXxDXNRLBtq",
    githubRepo: null,
    repoName: null,
    accent: "#22c55e",
    icon: "🏭",
  },
  {
    id: 4,
    title: "FairHire AI — Smart & Unbiased Hiring System",
    shortTitle: "FairHire AI",
    description: "An AI-powered hiring concept designed to detect and reduce bias in recruitment, aiming for fairer, more transparent candidate evaluation.",
    category: ["AI", "Web"],
    tags: ["AI", "React", "Bias Detection", "Fintech"],
    liveLink: "https://preview-react-9b6cru-ajhmu63dwjyizqmhsdz5ns.onspace.build/?_q=AJhmu63dwjyizQMHsdz5Ns",
    githubRepo: "https://github.com/Thanajayan143/FairHireAI",
    repoName: "FairHireAI",
    accent: "#a855f7",
    icon: "⚖️",
  },
  {
    id: 5,
    title: "Sri Sairam Great Learning Platform",
    shortTitle: "Great Learning Platform",
    description: "An e-learning concept platform for accessing courses and instruction, aimed at empowering students through smart, structured learning.",
    category: ["Web", "Academic Systems"],
    tags: ["React", "Onspace", "EdTech"],
    liveLink: "https://preview-react-9bgik1-gig7kl4v82pkxjdnbnk6na.onspace.build/?_q=Gig7kL4v82pkXjDnBnk6Na",
    githubRepo: null,
    repoName: null,
    accent: "#f59e0b",
    icon: "📚",
  },
  {
    id: 6,
    title: "Mentor-Student Academic Management Portal",
    shortTitle: "Mentor-Student Portal",
    description: "An academic management portal connecting mentors and students at Sri Sairam Engineering College, developed by ECE department students.",
    category: ["Academic Systems", "Web"],
    tags: ["React", "Onspace", "ECE Department"],
    liveLink: "https://preview-react-9bfrnj-9anw5ohaobd8d3ju9qu9bm.onspace.build/?_q=9anw5oHaobD",
    githubRepo: "https://github.com/Thanajayan143/MentorStudentPortal",
    repoName: "MentorStudentPortal",
    accent: "#06b6d4",
    icon: "👨‍🏫",
  },
  {
    id: 7,
    title: "Sairam Mentor Mentees Smart ERP System",
    shortTitle: "Smart ERP System",
    description: "The full Mentor-Mentee ERP system for Sri Sairam Engineering College — student, mentor, and admin modules in one platform, also packaged as a mobile APK.",
    category: ["Academic Systems", "Web", "Mobile"],
    tags: ["React", "Onspace", "Android APK", "Google Sign-In"],
    liveLink: "https://preview-react-9b5xjm-kyqbscftqy2nynapzi9gp8.onspace.build/?_q=KYQBSCFtqy2NynApZi9GP8",
    githubRepo: null,
    repoName: null,
    accent: "#00c4f5",
    isFeatured: true,
    icon: "🏛️",
  },
  {
    id: 8,
    title: "AI Fraud Early Warning System — Banking Security",
    shortTitle: "AI Fraud Detection",
    description: "An AI-based early-warning concept for detecting internal and privileged-user fraud in banking environments using real-time anomaly detection.",
    category: ["AI", "Cybersecurity"],
    tags: ["AI", "Anomaly Detection", "React", "Fintech Security"],
    liveLink: "https://preview-react-9bgzs0-5dqkxjfmxmvos4hthpjyyf.onspace.build/?_q=5dqkxjfmxMvos4HThpjY",
    githubRepo: null,
    repoName: null,
    accent: "#ef4444",
    icon: "🛡️",
  },
];

export const GITHUB_REPOS = [
  {
    name: "EduMate",
    description: "Student Mentoring & Document Management System for Sri Sairam Engineering College",
    language: "TypeScript",
    url: "https://github.com/Thanajayan143/EduMate",
    languageColor: "#3178c6",
  },
  {
    name: "FairHireAI",
    description: "Smart & Unbiased Hiring System using AI for bias detection in recruitment",
    language: "TypeScript",
    url: "https://github.com/Thanajayan143/FairHireAI",
    languageColor: "#3178c6",
  },
  {
    name: "MentorStudentPortal",
    description: "Academic management portal connecting mentors and students at SSEC",
    language: "TypeScript",
    url: "https://github.com/Thanajayan143/MentorStudentPortal",
    languageColor: "#3178c6",
  },
  {
    name: "MindCareAI",
    description: "AI-powered mental health awareness and support system",
    language: "TypeScript",
    url: "https://github.com/Thanajayan143",
    languageColor: "#3178c6",
  },
  {
    name: "MindCareAI-9bfomj",
    description: "Extended build of the MindCare AI project",
    language: "TypeScript",
    url: "https://github.com/Thanajayan143",
    languageColor: "#3178c6",
  },
  {
    name: "AGM-CRAKER",
    description: "Technical project in the security/tooling domain",
    language: "Python",
    url: "https://github.com/Thanajayan143",
    languageColor: "#3572A5",
  },
];

export const SKILLS = {
  "Software & Development": [
    "HTML", "CSS", "JavaScript", "React", "Node.js",
    "Web Development", "Mobile App Development", "Full Stack",
    "REST APIs", "Responsive Design", "Onspace Platform",
  ],
  "Cybersecurity": [
    "Security Fundamentals", "OSINT", "Threat Intelligence",
    "Kali Linux", "Security Awareness", "Ethical Research",
    "Bug Hunting", "Network Security", "Termux", "Web Security",
  ],
  "AI & Automation": [
    "AI Tools", "AI-Powered Products", "Automation Systems",
    "AI-Assisted Development", "Anomaly Detection",
    "AI + Cybersecurity", "AI + Education", "AI + IoT",
  ],
  "Hardware & IoT": [
    "Arduino", "Sensors", "Servo Motors", "OLED Displays",
    "TFT Displays", "IoT Systems", "Electronics Prototyping",
    "Embedded Systems", "Automation Hardware", "Tinkercad",
  ],
  "Tools & Platforms": [
    "GitHub", "VS Code", "Arduino IDE", "Termux",
    "Tinkercad", "Proteus", "Blender", "CapCut",
    "AI Dev Tools", "Onspace Platform",
  ],
};

export const TIMELINE_EVENTS = [
  {
    year: "Early",
    title: "Early Curiosity",
    description: "Growing up in Ariyalur, developed a natural curiosity for technology and electronics through GHSS school years.",
    icon: "🌱",
  },
  {
    year: "ECE",
    title: "Entered ECE at Sri Sairam",
    description: "Joined Sri Sairam Engineering College, Chennai, for Electronics & Communication Engineering — the foundation for deeper exploration.",
    icon: "🎓",
  },
  {
    year: "Code",
    title: "Programming Exploration",
    description: "Started exploring HTML, CSS, JavaScript. Built first web pages, discovered the power of code to bring ideas to life.",
    icon: "💻",
  },
  {
    year: "HW",
    title: "Arduino & Electronics",
    description: "Began hands-on experimentation with Arduino, sensors, servo motors, OLED displays. Built first working embedded prototypes.",
    icon: "⚡",
  },
  {
    year: "Web",
    title: "Web Development",
    description: "Leveled up to React and full-stack concepts. Started building real, deployable web applications with modern tooling.",
    icon: "🌐",
  },
  {
    year: "IoT",
    title: "IoT & Automation",
    description: "Combined hardware and software skills — built IoT concepts bridging physical sensors with digital interfaces.",
    icon: "🔌",
  },
  {
    year: "Sec",
    title: "Cybersecurity Exploration",
    description: "Began studying security fundamentals — OSINT, threat intelligence, ethical research using Kali Linux and security tooling.",
    icon: "🔒",
  },
  {
    year: "AI",
    title: "AI & Innovation",
    description: "Started building AI-powered product concepts — FairHire AI for unbiased recruitment, AI Fraud Detection for banking security.",
    icon: "🤖",
  },
  {
    year: "Hack",
    title: "Hackathons & Innovation",
    description: "Participated in the Sairam SDG Ideathon — built the Smart Industrial Air Monitoring & Worker Safety System concept.",
    icon: "🏆",
  },
  {
    year: "ERP",
    title: "Full ERP System",
    description: "Built the complete Sairam Mentor Mentees Smart ERP System — a full React web app with Android APK, Google Sign-In, and multi-role modules.",
    icon: "🏛️",
  },
  {
    year: "CEO",
    title: "Founded SaiNex Technologies",
    description: "Established SaiNex Technologies as a platform to build real digital products — web, mobile, AI, cybersecurity, IoT, and hardware under one brand.",
    icon: "🚀",
  },
  {
    year: "Now",
    title: "Building, Learning, Growing",
    description: "Currently: 2nd Year ECE student, Founder & CEO of SaiNex Technologies, building more projects across every domain, continuously learning.",
    icon: "✨",
  },
];

export const SAINEX_SERVICES = [
  { title: "Web Development", desc: "Modern, responsive web applications built with React and cutting-edge tooling.", icon: "🌐" },
  { title: "Mobile Applications", desc: "Cross-platform mobile apps including Android APK development.", icon: "📱" },
  { title: "AI Solutions", desc: "AI-powered product concepts — from hiring intelligence to fraud detection.", icon: "🤖" },
  { title: "Automation", desc: "Workflow automation combining software intelligence with process design.", icon: "⚙️" },
  { title: "Cybersecurity", desc: "Security awareness, ethical research, bug hunting, and defensive consulting.", icon: "🔒" },
  { title: "IoT Systems", desc: "Internet of Things solutions connecting hardware sensors to digital platforms.", icon: "🔌" },
  { title: "Arduino & Hardware", desc: "Embedded systems, sensor integration, and electronics prototyping.", icon: "⚡" },
  { title: "Technical Consulting", desc: "Engineering guidance for digital transformation and technology decisions.", icon: "💡" },
];

export const CONTACT = {
  email: "sec25ec477@sairamtap.edu.in",
  github: "https://github.com/Thanajayan143",
  instagram: "https://www.instagram.com/sainex_technologies",
  instagramHandle: "@sainex_technologies",
  linkedin: "https://www.linkedin.com/in/dhananjeyan-s",
};

export const PHOTOS = {
  hero: "https://cdn-ai.onspace.ai/onspace/project/uploads/7u7PuKzW3iaDF42FSWL7X7/founder-dhananjeyan.png",
  founder: "https://cdn-ai.onspace.ai/onspace/project/uploads/PJq7SVUJu4E8X93R6Vrqy5/file_00000000899471f5bda6685f4cddc620.png",
  logoText: "https://cdn-ai.onspace.ai/onspace/project/uploads/nrZcf9EBNvS5Me7nnjyYKP/Picsart_26-06-30_21-10-42-823.jpg",
  logoFull: "https://cdn-ai.onspace.ai/onspace/project/uploads/9Ykik2nYTA82zmyyqFLPTJ/IMG_20260630_212630_828.webp",
  logoAlt: "https://cdn-ai.onspace.ai/onspace/project/uploads/oG96gjG6SReRziixwA9GQi/IMG_20260701_020723_983.jpg",
};
